export const banner= [
  {
  id: '1',
  name: 'Grains',
  image: require('../assets/images/items/wheat_item_1.png'),
  productName: 'Wheat',
  price: '₹20/kg',
  minOrderQty: '50 kg',
  location: 'Maharashtra, India',
  farmerName:'Chinmay',
},
{
  id: '2',
  name: 'Fruits',
  image: require('../assets/images/items/mango_item_1.png'),
  productName: 'Mango',
  price: '₹5/pc',
  minOrderQty: '100 pcs',
  location: 'Ratnagiri, India',
  farmerName:'Rudra',
},
{
  id: '3',
  name: 'Vegetables',
  image: require('../assets/images/items/carrot_item_1.png'),
  productName: 'Carrot',
  price: '₹2/kg',
  minOrderQty: '30 kg',
  location: 'Nashik, India',
  farmerName:'Sanket'
},
{
  id: '4',
  name: 'Flowers',
  image: require('../assets/images/items/rose_item_1.png'),
  productName: 'Rose',
  price: '₹1/stem',
  minOrderQty: '200 stems',
  location: 'Bangalore, India',
  farmerName:'Danish',
},
{
  id: '5',
  name: 'Spices and Herbs',
  image: require('../assets/images/items/turmeric_item_1.png'),
  productName: 'Turmeric',
  price: '₹1/kg',
  minOrderQty: '20 kg',
  location: 'Erode, India',
  farmerName:'Aashish',
},
];