export const recommended_products =[{
  id : '1',
  name : 'Vegetables',
  image : require('../assets/images/recommendation/Hybrid_Fresh_Tomato.png'),
  productName: 'Hybrid Fresh Tomato',
  price: '₹20/kg',
  minOrderQty: '20 kg',
  location: 'kolkata, India',
  farmerName:'Lokesh'
  },
  {
  id : '2',
  name : 'Spices and Herbs',
  image : require('../assets/images/recommendation/Jeera(Cumin_Seed).png'),
  productName: 'Jeera(Cumin Seed)',
  price: '₹350/kg',
  minOrderQty: '5 kg',
  location: 'Bihar, India',
  farmerName:'Chandani',  
  },
  {
  id : '3',
  name : 'Spices and Herbs',
  image : require('../assets/images/recommendation/Raw_Turmeric_Fingers.png'),
  productName: 'Raw Turmeric Fingers',
  price: '₹40/kg',
  minOrderQty: '50 kg',
  location: 'Ranchi, India', 
  farmerName:'Atharv',
  },
  {
  id : '4',
  name : 'Vegetables',
  image : require('../assets/images/recommendation/Fresh_Carrot.png'),
  productName: 'Fresh Carrots',
  price: '₹20/kg',
  minOrderQty: '30 kg',
  location: 'Hyderabad, India',  
  farmerName:'Rihan',
  },
  {
  id : '5',
  name : 'Flowers',
  image : require('../assets/images/recommendation/Rose_Plants.png'),
  productName: 'Rose Plants',
  price: '₹15/plant',
  minOrderQty: '25 plants',
  location: 'Noida, India',
  farmerName:'Devesh',  
  },
  {
  id : '6',
  name : 'Dairy Products',
  image : require('../assets/images/recommendation/Farm_Fresh_Milk.png'),
  productName: 'Farm Fresh Milk',
  price: '₹60/litre',
  minOrderQty: '20 litre',
  location: 'Shivaji Nagar,Jaipur, India',  
  farmerName:'Sujal',
  },
  {
  id : '7',
  name : 'Dry Fruits',
  image : require('../assets/images/recommendation/almonds.png'),
  productName: 'Almonds',
  price: '₹450/kg',
  minOrderQty: '5 kg',
  location: 'Bengaluru, India',  
  farmerName:'Shreya',
  },
  {
  id : '8',
  name : 'Exotic Fruits',
  image : require('../assets/images/recommendation/A_Grade_Fresh_Kiwi_Fruits.png'),
  productName: 'A Grade Fresh Kiwi Fruits',
  price: '150/kg',
  minOrderQty: '20 kg',
  location: 'Varanasi, India',  
  farmerName:'Tanish',
  },
  {
  id : '9',
  name : 'Grains',
  image : require('../assets/images/recommendation/Composite_Pearl_Millet(Bajra).png'),
  productName: 'Composite Pearl Millet (Bajra)',
  price: '₹25/kg',
  minOrderQty: '50 kg',
  location: 'Udaipur, India',  
  farmerName:'Kanak',
  },
  ]